"""Добавление в таблицу результатов имя и группу студентов

Revision ID: 7a2ac4653a9a
Revises: dd13567cd18d
Create Date: 2026-02-20 13:41:55.314434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2ac4653a9a'
down_revision: Union[str, Sequence[str], None] = 'dd13567cd18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('student_name', sa.String(), nullable=True))
    op.add_column('results', sa.Column('student_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'student_group')
    op.drop_column('results', 'student_name')
    # ### end Alembic commands ###
