"""Добавление в таблицу резульатов max_id

Revision ID: 7af46030428f
Revises: c287e893131f
Create Date: 2026-02-20 12:42:17.081465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af46030428f'
down_revision: Union[str, Sequence[str], None] = 'c287e893131f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('student_max_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_results_student_max_id'), 'results', ['student_max_id'], unique=False)
    op.drop_constraint(op.f('results_student_id_fkey'), 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'students', ['student_id'], ['id'], ondelete='SET NULL')
    op.drop_column('results', 'student_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('student_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key(op.f('results_student_id_fkey'), 'results', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_results_student_max_id'), table_name='results')
    op.drop_column('results', 'student_max_id')
    # ### end Alembic commands ###
