"""Добавление в таблицу заданий  max_id

Revision ID: dd13567cd18d
Revises: 7af46030428f
Create Date: 2026-02-20 13:29:56.798281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd13567cd18d'
down_revision: Union[str, Sequence[str], None] = '7af46030428f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('author_max_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_assignments_author_max_id'), 'assignments', ['author_max_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_author_max_id'), table_name='assignments')
    op.drop_column('assignments', 'author_max_id')
    # ### end Alembic commands ###
